### ISSUE TITLE
Calling populate() gets TypeError: Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by mblackritter** [holidayextras/jsonapi-store-relationaldb#89]
I'm just setting up jsonapi-server to mock our JSON:API, but while I try to populate the DB, I get the following error:

```
/aniola-cotesco-se/node_modules/jsonapi-store-relationaldb/lib/sqlHandler.js:105
      self.baseModel.sync(options).asCallback(cb)
                    ^

TypeError: Cannot read property 'sync' of undefined
    at /aniola-cotesco-se/node_modules/jsonapi-store-relationaldb/lib/sqlHandler.js:105:21
    at /aniola-cotesco-se/node_modules/async/dist/async.js:3853:24
    at replenish (/aniola-cotesco-se/node_modules/async/dist/async.js:946:17)
```

I kept my resource file very simple and already tried to remove the attributes, but that doesn't make a difference:

```javascript
jsonApi.define({
  namespace: 'json:api',
  resource: 'settings',
  handlers: dbHandler,
  attributes: {
    title: jsonApi.Joi.string().required()
      .description('The articles title, should be between 8 and 15 words')
      .example('Learning how to use JSON:API'),
    content: jsonApi.Joi.string().required()
      .description('The main body of the article, provided as HTML')
      .example('<p>Paragraph 1. Lovely.</p><hr /><p>The End.</p>'),
    created: jsonApi.Joi.string().regex(/^[12]\d\d\d-[01]\d-[0123]\d$/)
      .description('The date on which the article was created, YYYY-MM-DD')
      .example('2017-05-01'),
    status: jsonApi.Joi.string().default('published')
      .description('The status of the article - draft, ready, published')
      .example('published'),
    views: jsonApi.Joi.number().default(0)
      .description('Number of views for this article')
  }
})
```

What might it be that I'm not aware of? 🤗

**Comment by paparomeo** [comment]
Your error is unexpected. I'll try to reproduce it locally to gain more insight.

**Comment by 2ZZ** [comment]
I also have this issue, node version doesn't seem to make a difference

**Comment by vnen** [comment]
I bumped into this. Looking at the source I discovered that you can only call `populate()` **after** you called `jsonApi.start()`.

**Comment by longnguyen2306** [comment]
I also have this problem, is there any solution already?

**Comment by longnguyen2306** [comment]
> I bumped into this. Looking at the source I discovered that you can only call `populate()` **after** you called `jsonApi.start()`.

What does that mean for us developers?

**Comment by longnguyen2306** [comment]
Thank to vnen I think I figured this out. Kind of stupid:

You cann't populate the database directly after creating the handler. 

Call handler.populate after defining the database resource. In my case:

```
'use strict';

const jsonApi = require('jsonapi-server');

const handler = require('../handlers/handler');

jsonApi.define({
  resource: "userCourseHighscore",
  handlers: handler,
  attributes: {
    userId: jsonApi.Joi.string(),
    courseId: jsonApi.Joi.string(),
    score: jsonApi.Joi.number(),
    createdAt: jsonApi.Joi.date(),
    updatedAt: jsonApi.Joi.date()
  }
});

handler.populate();

```
