### ISSUE TITLE
Promises are being created but not being returned

### ISSUE THREAD

**Issue by DuncanFenning** [holidayextras/jsonapi-store-relationaldb#9]
Every time breakPromise is being called I get a promise warning:

```
Warning: a promise was created in a  handler but was not returned from it
    at process._tickDomainCallback (node.js:463:13)
From previous event:
    at Function.each (/Users/duncan.fenning/git/hapi/node_modules/jsonapi-store-relationaldb/node_modules/sequelize/lib/promise.js:21:17)
    at Sequelize.drop (/Users/duncan.fenning/git/hapi/node_modules/jsonapi-store-relationaldb/node_modules/sequelize/lib/sequelize.js:1008:18)
    at Promise.try.then.then.models (/Users/duncan.fenning/git/hapi/node_modules/jsonapi-store-relationaldb/node_modules/sequelize/lib/sequelize.js:941:19)
    at process._tickDomainCallback (node.js:463:13)
    at Function.Module.runMain (module.js:499:11)
From previous event:
    at Promise.then (/Users/duncan.fenning/git/hapi/node_modules/jsonapi-store-relationaldb/node_modules/sequelize/lib/promise.js:21:17)
    at Sequelize.sync (/Users/duncan.fenning/git/hapi/node_modules/jsonapi-store-relationaldb/node_modules/sequelize/lib/sequelize.js:939:6)
    at SqlStore.populate (/Users/duncan.fenning/git/hapi/node_modules/jsonapi-store-relationaldb/lib/sqlHandler.js:47:31)
    at SqlStore.initialise (/Users/duncan.fenning/git/hapi/node_modules/jsonapi-store-relationaldb/lib/sqlHandler.js:41:8)
    at Object.jsonApi.define (/Users/duncan.fenning/git/hapi/node_modules/jsonapi-server/lib/jsonApi.js:57:29)
    at Object.<anonymous> (/Users/duncan.fenning/git/hapi/jsonApi/bookings.js:6:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Array.forEach (native)
    at module.exports (/Users/duncan.fenning/git/hapi/jsonApi.js:63:6)
    at Object.<anonymous> (/Users/duncan.fenning/git/hapi/server.js:140:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by hxoliverrumbelow** [comment]
This only occurs when the `NODE_ENV` environment variable is set to `development`: http://bluebirdjs.com/docs/api/environment-variables.html

The warning explanation is here:
https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

We get the warning because we're missing a `return` statement somewhere, but it's intentional because we're terminating the promise chain... Unless I've missed something?

**Comment by pmcnr-hx** [comment]
This was an issue due to a Bluebird update (fixed [here](https://github.com/sequelize/sequelize/pull/4862)). Updating Sequelize to `3.14.2` removes the warning.
